### ISSUE TITLE
Probable new issue(s) in the "polymode" family (seen on Sep 6, 2018)

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [polymode/polymode#170] opened 2018-09-06 12:47 UTC
At installation of new versions, I get a few warnings. From my `*Messages*` buffer : 
```
Leaving directory ‘/home/charpent/.emacs.d/elpa/polymode-20180906.25’

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/poly-lock.el at Thu Sep  6 14:21:42 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/polymode-20180906.25/’

In poly-lock--extend-region-span:
poly-lock.el:331:57:Warning: reference to free variable ‘old-len’
poly-lock.el:337:1:Warning: Unused lexical argument ‘old-len’

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-base.el at Thu Sep  6 14:21:42 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-classes.el at Thu Sep  6 14:21:42 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-compat.el at Thu Sep  6 14:21:42 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-core.el at Thu Sep  6 14:21:42 2018
polymode-core.el:821:1:Warning: Unused lexical variable ‘mode’

In pm-map-over-modes:
polymode-core.el:838:49:Warning: reference to free variable ‘pos’
polymode-core.el:841:26:Warning: assignment to free variable ‘end1’
polymode-core.el:842:19:Warning: reference to free variable ‘end1’

In pm-get-mode-symbol-from-name:
polymode-core.el:1119:45:Warning: ‘dummy’ is an obsolete variable (as of
    25.1); use 'dummy instead

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-debug.el at Thu Sep  6 14:21:42 2018

In end of data:
polymode-debug.el:457:1:Warning: the function ‘pm-debug-toggle-verbose’ is not
    known to be defined.

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-export.el at Thu Sep  6 14:21:42 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-methods.el at Thu Sep  6 14:21:43 2018
polymode-methods.el:179:1:Warning: Unused lexical argument ‘type’

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-tangle.el at Thu Sep  6 14:21:43 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-weave.el at Thu Sep  6 14:21:43 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode.el at Thu Sep  6 14:21:43 2018

Compiling no file at Thu Sep  6 14:21:44 2018
Leaving directory ‘/home/charpent/.emacs.d/elpa/poly-noweb-20180906.26’

Compiling file /home/charpent/.emacs.d/elpa/poly-noweb-20180906.26/poly-noweb.el at Thu Sep  6 14:21:44 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/poly-noweb-20180906.26/’
poly-noweb.el:98:1:Warning: defcustom for ‘pm-host/latex-for-noweb’ fails to
    specify containing group
poly-noweb.el:98:1:Warning: defcustom for ‘pm-host/latex-for-noweb’ fails to
    specify containing group
poly-noweb.el:121:1:Error: No pm-polymode config object with name ‘pm-poly/pm-poly/noweb’

Compiling no file at Thu Sep  6 14:21:45 2018
Leaving directory ‘/home/charpent/.emacs.d/elpa/poly-markdown-20180906.25’

Compiling file /home/charpent/.emacs.d/elpa/poly-markdown-20180906.25/poly-markdown.el at Thu Sep  6 14:21:45 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/poly-markdown-20180906.25/’

In poly-markdown-mode:
poly-markdown.el:124:18:Warning: function poly-markdown-mode used to take 0+
    arguments, now takes 0-1
```

Starting a new `emacs` process fails : 
```
Warning (initialization): An error occurred while loading ‘/home/charpent/.emacs’:

Invalid slot type: pm-inner-chunkmode, head-matcher, (or string symbol cons), #[257 \302\300\301#\207 [markdown-yaml-metadata-begin nil pm--get-property-nearby] 5 

(fn AHEAD)]

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
De-installing, then reinstalling poly-R, poly-markdown, poly-noweb, polymode and markdown-mode still gives me a couple of warnings and a couple of errors : 
```
Leaving directory ‘/home/charpent/.emacs.d/elpa/polymode-20180906.25’

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/poly-lock.el at Thu Sep  6 14:35:04 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/polymode-20180906.25/’

In poly-lock--extend-region-span:
poly-lock.el:331:57:Warning: reference to free variable ‘old-len’
poly-lock.el:337:1:Warning: Unused lexical argument ‘old-len’

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-base.el at Thu Sep  6 14:35:04 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-classes.el at Thu Sep  6 14:35:04 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-compat.el at Thu Sep  6 14:35:04 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-core.el at Thu Sep  6 14:35:04 2018
polymode-core.el:821:1:Warning: Unused lexical variable ‘mode’

In pm-map-over-modes:
polymode-core.el:838:49:Warning: reference to free variable ‘pos’
polymode-core.el:841:26:Warning: assignment to free variable ‘end1’
polymode-core.el:842:19:Warning: reference to free variable ‘end1’
polymode-core.el:935:1:Warning: Unused lexical variable ‘poly-lock-allow-fontification’

In pm-get-mode-symbol-from-name:
polymode-core.el:1119:45:Warning: ‘dummy’ is an obsolete variable (as of
    25.1); use 'dummy instead

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-debug.el at Thu Sep  6 14:35:05 2018

In end of data:
polymode-debug.el:457:1:Warning: the function ‘pm-debug-toggle-verbose’ is not
    known to be defined.

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-export.el at Thu Sep  6 14:35:05 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-methods.el at Thu Sep  6 14:35:05 2018
polymode-methods.el:179:1:Warning: Unused lexical argument ‘type’

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-tangle.el at Thu Sep  6 14:35:05 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode-weave.el at Thu Sep  6 14:35:05 2018

Compiling file /home/charpent/.emacs.d/elpa/polymode-20180906.25/polymode.el at Thu Sep  6 14:35:05 2018

Compiling no file at Thu Sep  6 14:35:06 2018
Leaving directory ‘/home/charpent/.emacs.d/elpa/poly-noweb-20180906.26’

Compiling file /home/charpent/.emacs.d/elpa/poly-noweb-20180906.26/poly-noweb.el at Thu Sep  6 14:35:06 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/poly-noweb-20180906.26/’
poly-noweb.el:98:1:Warning: defcustom for ‘pm-host/latex-for-noweb’ fails to
    specify containing group
poly-noweb.el:98:1:Warning: defcustom for ‘pm-host/latex-for-noweb’ fails to
    specify containing group
poly-noweb.el:121:1:Error: No pm-polymode config object with name ‘pm-poly/pm-poly/noweb’

Compiling no file at Thu Sep  6 14:35:10 2018
Leaving directory ‘/home/charpent/.emacs.d/elpa/markdown-mode-20180904.1601’

Compiling file /home/charpent/.emacs.d/elpa/markdown-mode-20180904.1601/markdown-mode.el at Thu Sep  6 14:35:10 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/markdown-mode-20180904.1601/’

Compiling no file at Thu Sep  6 14:35:11 2018
Leaving directory ‘/home/charpent/.emacs.d/elpa/poly-markdown-20180906.25’

Compiling file /home/charpent/.emacs.d/elpa/poly-markdown-20180906.25/poly-markdown.el at Thu Sep  6 14:35:11 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/poly-markdown-20180906.25/’
poly-markdown.el:124:1:Error: No pm-polymode config object with name ‘pm-poly/pm-poly/markdown’

Compiling no file at Thu Sep  6 14:35:13 2018
Leaving directory ‘/home/charpent/.emacs.d/elpa/poly-R-20180904.1528’

Compiling file /home/charpent/.emacs.d/elpa/poly-R-20180904.1528/poly-R.el at Thu Sep  6 14:35:13 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/poly-R-20180904.1528/’
poly-R.el:89:1:Error: No pm-polymode config object with name ‘pm-poly/markdown+R’

Compiling no file at Thu Sep  6 14:35:14 2018
Leaving directory ‘/home/charpent/.emacs.d/elpa/markdown-mode-20180904.1601’

Compiling file /home/charpent/.emacs.d/elpa/markdown-mode-20180904.1601/markdown-mode.el at Thu Sep  6 14:35:14 2018
Entering directory ‘/home/charpent/.emacs.d/elpa/markdown-mode-20180904.1601/’
```
I get the same error as before when starting a new process : 
```
Warning (initialization): An error occurred while loading ‘/home/charpent/.emacs’:

Invalid slot type: pm-inner-chunkmode, head-matcher, (or string symbol cons), #[257 \302\300\301#\207 [markdown-yaml-metadata-begin nil pm--get-property-nearby] 5 

(fn AHEAD)]

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

HTH...

**Comment by dogcaesar** [comment] 2018-09-06 14:11
same problem here in a fresh installation of Emacs 26.1 in OSX

**Comment by vspinu** [comment] 2018-09-06 14:33
Indeed. There are a bunch of issues with melpa version of packages which I don't see when I load from source. I wonder why that is happening. Looking into it.

**Comment by EmmanuelCharpentier** [comment] 2018-09-06 14:47
Can you suggest a workaround ? I had to remove poly* and revert to `Rnw-mode`, and that works only for `.Rnw`. For .Rmd, I'm stuck with `markdown-mode` and manual compilation.

**Comment by dogcaesar** [comment] 2018-09-06 14:51
I fixed the problem manually installing from source as @vspinu suggested (instructions [here](https://polymode.github.io/installation/)).
Looking forward to the permanent fix.

**Comment by vspinu** [comment] 2018-09-06 15:13
The problem is that the source and the melpa are actually the same. But the error occurs only with MELPA. 

I haven't figured out a way to reproduce the problem locally but I have pushed a fix which should address it. 

> Can you suggest a workaround ?

The workaround is always to delete the most recent directory from ELPA folder and  revert to the previously installed polymode. I am afraid things are still a bit unstable and could break. I still keep changing the core in in non-trivial ways.

**Closed** 2018-09-06 19:42 UTC
