### ISSUE TITLE
`ess-smart-S-assign` doesn't work in poly-markdown+r-mode

### ISSUE THREAD

**Issue by plantarum** [polymode/polymode#147] opened 2018-01-26 16:42 UTC
Steps to reproduce:

- emacs -Q
- load the following config:

```
(require 'package)
(setq package-load-list
      '((ess t)
        (julia-mode t)
        (polymode t)))
(package-initialize)
(require 'poly-R)
(require 'poly-markdown)
```

- load an Rmarkdown file
- switch to `poly-markdown+r-mode`
- create and R code block:

    \```{r}
    X
    \```

- with point at `X`, type `_`

What I expect: Emacs inserts `<-`

What happens: Emacs inserts `_`.

I checked to see that `_` is properly bound to `ess-smart-S-assign`, and it is. edebugging `ess-smart-S-assign` reveals that Emacs thinks it's inside a string that is bound by character 96, i.e., `\``, so perhaps something about the back-tick 'fence' is causing the problem? As a work-around, I have commented out the line that calls `ess-inside-string-or-comment-p` in `ess-smart-S-assign`, which fixes the problem (and of course breaks `ess-smart-S-assign` when used inside an actual string or comment).

emacs version: 26.0.90, 2017-12-21
ess version: 17.11
polymode version: 2017-0307.322 (the latest version on melpa I think)

**Comment by theGreatWhiteShark** [comment] 2018-04-26 12:08
Same here.

Inside the `ess-smart-S-assign` function Emacs checks if the point (cursor) is in either a string or a comment. If true, the underscore `_` and in all other cases the assign symbol `<-` is returned.

To check the condition above, the `syntax.ppss` function is used, which returns the parser state at point https://www.gnu.org/software/emacs/manual/html_node/elisp/Parser-State.html#Parser-State

The  fourth element of the parser-state is the one messing things up in here. It tells Emacs if the point is inside a string or not. And if so, it returns the last character of the string. Since the last character is 96, which corresponds to **`**, it's save to assume that ESS recognizes the whole code chunk as a comment and therefore does not generate the assign symbol.

Probably there were some default parameters changed in the transition from Emacs25.3 (where the problem does not occur) to Emacs26.For Emacs27.0.50 (the version I do use) the bug still remains.

**Comment by theGreatWhiteShark** [comment] 2018-04-26 13:11
A quick (and dirty) solution is to add a commented backquote at the beginning of each chunk 
```
##`
```

This will fool the `syntax-ppss` function in thinking the "string" started with the third backquote at the beginning of the R code chunk is closed. At the same it will be ignored by the R interpreter since it is placed in a comment.

**Comment by timflutre** [comment] 2018-06-23 15:04
When exporting the Rmd file into, say, html, using `##'` creates a header.

My workaround (good enough for me at least) to insert ` <- ` when entering `_` is to add a global key binding to `.emacs`:

```
(global-set-key (kbd "C-c =") " <- ")
```

There should be a way to define a local keybinding instead, specific to ess-mode, but I don't know how to do that.

**Comment by theGreatWhiteShark** [comment] 2018-06-24 10:21
Sorry for being not precise enough. The ``##` `` has to be inserted **at the beginning of the first R chunk**. There the R interpreter just ignores it as any other comment and apart from having it printed when using the chunk option *eval=TRUE* it doesn't interfere with you code.

So the document should look like

````
 # Markdown header

Markdown text

```{r 'first-r-chunk'}
##`
x <- rand( 1 )
```
````

Also be sure to use a backtick `` ##` `` instead a single quote `` ##' ``.

**Comment by timflutre** [comment] 2018-06-25 07:06
@theGreatWhiteShark thanks a lot!

**Comment by piklprado** [comment] 2018-07-13 06:05
Thanks @theGreatWhiteShark. The bug affects also [ElDoc](http://ess.r-project.org/Manual/ess.html#ESS-ElDoc) and your solution takes care of this too.

**Comment by theGreatWhiteShark** [comment] 2018-07-22 17:07
I just took a look into this bug again and the problem is not due to **polymode** but to **ESS** mode itself. In the *lisp/ess-r-mode.el* file of the ESS source the \` symbol is defined as a string delimiter in the corresponding syntax table. This causes `syntax-ppss` and thus also `ess-smart-S-assign` to think the point is actually inside a string instead of a R code chunk.

As a fix (a proper fix compared to the `` ##` `` one above) you can add the following lines to your .emacs configuration file

``` lisp
(add-hook 'ess-mode-hook
	  (lambda()
	    ;; Copy the syntax table of the ESS-mode and set the "`"
	    ;; symbol to a paired delimiter. Else, functions like
	    ;; `ess-smart-S-assign` won't work as expected in
	    ;; `polymode`.
	    (setq ess-r-syntax-table-modified
		  (make-syntax-table ess-r-syntax-table))
	    (modify-syntax-entry ?` "$" ess-r-syntax-table-modified)
	    (set-syntax-table ess-r-syntax-table-modified)))
```

This will duplicate the syntax table of ESS and changes the definition of the \` symbol from a string delimiter to a paired delimiter.

**Comment by piklprado** [comment] 2018-07-24 03:30
Thanks a bunch!

**Comment by theGreatWhiteShark** [comment] 2018-07-24 09:02
But this is still a bug of **polymode** and is interfering with the `ess-smart-S-assign` function.

Whenever there is an uneven number of `'`, `"`, or `%` symbols in the buffer *above* the R chunk (all of them are handled as string delimiters), `_` won't expend to the `<-` symbol either. 

This is probably due to the `syntax-ppss` function, which looks at all the buffer till `point` and thus also includes all previous chunks and not just the one at hand. Not quite sure if this behavior can be controlled by narrowing but I'm confident this problem can be solved with a local version of the function taking care of chunk's scope.

**Comment by vspinu** [comment] 2018-08-04 12:46
This is actually emacs 26 issue. The caching system of syntax-ppss was changed radically and is unfortunately somewhat unfriendly to polymode. I will have to bring this up on emacs devel.

In the meanwhile, the syntax and font-lock issues should be fixed in the `next` branch. It will take  another week or longer  till it's merged into master because I am currently re-writing and re-organizing the package. Would appreciate if people could try it from source and report issues.

**Closed** 2018-08-30 23:09 UTC
Labels: bug
