### ISSUE TITLE
Broken syntax highlighting in Markdown mode

### ISSUE THREAD

**Issue by cpitclaudel** [polymode/polymode#212] opened 2019-03-15 13:01 UTC
Hi there,

I just installed this mode to try it out.  I used the README file at https://github.com/cpitclaudel/biblio.el/blob/master/README.md as a test for poly-markdown.

Unfortunately, markdown highlighting seems broken: here's a screenshot:
![Screenshot from 2019-03-15 08-59-03](https://user-images.githubusercontent.com/8181630/54432861-44c91600-4722-11e9-937d-f40d11cf5e92.png)

Notice how the link is being highlighted as an Elisp parenthesis, and the Markdown titles are not highlighted.
Am I doing something wrong?

Thanks!

**Comment by vspinu** [comment] 2019-03-15 13:11
I don't see this with emacs 26 nor 27. Make sure you are using the most recent markdown/polymode/ and poly-markdown.

![Screenshot_20190315_140812](https://user-images.githubusercontent.com/1363467/54433475-341d9d80-472c-11e9-8f08-9147a07dfa0a.png)

**Comment by vspinu** [comment] 2019-03-15 13:15
It's relatively easy to check if it's your setup. git clone poly-markdown and do `make start` from within. It should fetch all recent dependencies and open a clean emacs for you.

**Comment by cpitclaudel** [comment] 2019-03-15 13:37
Very convenient, thanks! If I press -x font-lock-fontify-buffer, everything gets highlighted properly.  But not when I first open the file.

I found a partial repro in -Q mode by adding the path of the README file to the command line invocation:

```
$ make start
EMACS VERSION: 27.0.50
emacs -Q -L . -L modes -L tests -L .ELPA/27.0.50 --batch --load targets/melpa.el
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Contacting host: melpa.org:443
Package refresh done
INSTALLED DEPS: yaml-mode:(20180409 607) polymode:(20190315 606) markdown-mode:(20190305 319)
emacs -Q -L . -L modes -L tests -L .ELPA/27.0.50 -L . \
	--load targets/melpa-init.el \
	--load tests/*.el \
	~/.emacs.d/lisp/biblio.el/README.md
```

When I do this, the buffer is first displayed completely unfontified; then when I press a key everything is fontified as expected:

![Screenshot from 2019-03-15 09-37-07](https://user-images.githubusercontent.com/8181630/54435029-798b9c00-4727-11e9-87e7-9470e300369d.png)

![Screenshot from 2019-03-15 09-37-17](https://user-images.githubusercontent.com/8181630/54435034-7c868c80-4727-11e9-94cb-f56112a10941.png)

**Comment by vspinu** [comment] 2019-03-15 15:24
> I found a partial repro in -Q 

I see this indeed. Any key, including navigation, would do the trick. Hard to say what could be causing it. I noticed that on e26 and 27 some buffers, under some conditions are not re-displayed till a new user input. This case looks very similar. 

But I don't think your  OP issue has anything to do with it. I have made quite a few low level changes over past week, so things might be broken here and there. I will address two fontification related issues which I can reproduce over the weekend. Those might address yours as well.

**Comment by cpitclaudel** [comment] 2019-03-15 15:28
Thanks a lot. Please ping me when you need me to test again :)

**Comment by vspinu** [comment] 2019-03-17 08:27
@cpitclaudel I have fixed the font-lock issues that I had in mind. Would you mind trying again?

**Comment by cpitclaudel** [comment] 2019-03-17 19:15
Thanks, the fix work in `make start`.  I will try to pin the source of the original issue, as indeed these fixes didn't fix the original issue.

**Comment by vspinu** [comment] 2019-03-18 19:35
There are a few hard problems with the fontification in multi-modes, so perfect solutions are unlikely, but close to perfect is possible. I keep fixing subtle issues, so keep updated. The issue might go away by itself.

**Comment by vspinu** [comment] 2019-04-14 11:24
@cpitclaudel did you have a chance to figure out what is causing it? There have been more fixes in the master BTW.

I have run a few comprehensive checks on your file and nothing showed up. As I can no longer think of any further improvements that can magically fix your issue, I would like to close this one unless you could provide something to work with.

**Comment by cpitclaudel** [comment] 2019-04-23 22:40
I tracked this down to this:

```
(add-hook 'emacs-lisp-mode-hook #'nameless-mode)
```

(`nameless-mode` is provided by the `nameless` package).  I was able to reproduce the issue by just running `make start` and then running `M-: (add-hook 'emacs-lisp-mode-hook #'nameless-mode)` before opening that README file.

Does that reproduce the issue for you too?

**Comment by vspinu** [comment] 2019-04-24 08:33
I can reproduce. Thanks! 

I am reasonably confident that it's because nameless calls `font-lock-fontify-region-function` on the entire buffer during the initialization. I will see if I can fix this generically.

**Closed** 2019-04-26 17:30 UTC
Labels: compat, font-lock

**Comment by larebsyed** [comment] 2020-08-06 21:22
@vspinu I don't this is fixed, I am seeing this issue with Typescript-tsx-mode
