### ISSUE TITLE
Syntax highlighting broken on HEAD (works on 0.2.2)

### ISSUE THREAD

**Issue by jsmestad** [polymode/polymode#270] opened 2020-06-05 23:14 UTC
## Background

While writing this blog post on [enabling web-mode highlighting with Elixir templates](https://blog.evalcode.com/phoenix-liveview-inline-syntax-highlighting-for-emacs/), I tracked down that `0.2.2` release of polymode works as expected. While something about the last 2 commits to the repo break things.

If you check out the blog you can see what I am doing. Did something get deprecated or did the commits introduce a bug?

**Comment by vspinu** [comment] 2020-06-06 10:23
Hmm, It might be yesterday's fix of #269. It looked pretty harmless to me. What's the problem more concretely?

**Comment by vspinu** [comment] 2020-06-06 11:25
I have tried your code with current an stable version. It all works the same for me. There is indeed a font lock issue when the file is first opened, but once the editing starts it seems to work ok.

**Comment by jsmestad** [comment] 2020-06-06 17:02
@vspinu if you can keep this open a few days, I'll have a bit more time to play with it and see what I can figure out.

**Comment by andrew-anguiano** [comment] 2021-10-10 00:26
I'm also having issues with getting any highlighting in ~L or ~H blocks after following the steps in OP's blog post. I'm also newer to emacs and am using Doom. Any help is greatly appreciated! 

I _am_ seeing the following message in my buffer: `jit-lock--run-functions 18362 19616) [span 18156 19616  game_live.ex[web]] -> (font-lock-default-fontify-region 18362 19616): Args out of range: 1, 1`

Here is my config: 
```
(use-package polymode
  :mode ("\.ex$" . poly-elixir-web-mode)
  :config
  (define-hostmode poly-elixir-hostmode :mode 'elixir-mode)
  (define-innermode poly-liveview-expr-elixir-innermode
    :mode 'web-mode
    :head-matcher (rx line-start (* space) (or "~L" "~H") (= 3 (char "\"'")) line-end)
    :tail-matcher (rx line-start (* space) (= 3 (char "\"'")) line-end)
    :head-mode 'host
    :tail-mode 'host
    :allow-nested nil
    :keep-in-mode 'host
    :fallback-mode 'host)
  (define-polymode poly-elixir-web-mode
    :hostmode 'poly-elixir-hostmode
    :innermodes '(poly-liveview-expr-elixir-innermode))
  )
(setq web-mode-engines-alist '(("elixir" . "\\.ex\\'")))
```

**Comment by d3caf** [comment] 2021-12-02 21:06
@jsmestad thanks so much for this. Looks like it works with your tweaked config, I just switched the `L` to `H`. It's a bit wonky still -- I use Doom/evil so I have to enter insert mode before it'll recognize the inner chunk and it seems to lose it if I go back to normal mode and scroll around a bit. Much much better than nothing though!

Thanks again :)

**Comment by d3caf** [comment] 2021-12-08 15:43
Just an update: upon further use, I still am getting the fontify issues which breaks the highlighting. It's quite possible there's another package causing issues. `(jit-lock--run-functions 350 888) [span 350 888  report_table.ex[web]] -> (font-lock-default-fontify-region 350 888): Args out of range: 1, 1`

**Comment by anildigital** [comment] 2022-01-19 06:53
I am facing similar errors and have created the issue https://github.com/polymode/polymode/issues/308

**Comment by vspinu** [comment] 2022-01-19 10:22
Problem identified upstream and proposed a fix.

**Comment by vspinu** [comment] 2022-01-19 12:12
Upstream merged. Problem fixed on my side. Please reopen if you still see `jit-lock--run-functions` error.

**Closed by vspinu** 2022-01-19 12:12 UTC

**Comment by d3caf** [comment] 2022-01-19 15:57
@vspinu thanks a lot for that! Unfortunately, I'm still seeing the `jit-lock--run-functions` issue:
`(jit-lock--run-functions 373 859) [span 327 859  test.ex[web]] -> (font-lock-default-fontify-region 373 859): Args out of range: 1, 1`

I've confirmed I'm on HEAD as well.

**Comment by anildigital** [comment] 2022-01-19 16:00
@d3caf I guess you tried it after upgrading both web-mode and polymode. Here is my Emacs config 

```elisp
(use-package
   polymode
  :ensure t
  :mode ("\\.ex\\'" . poly-elixir-web-mode)
  :init (setq web-mode-engines-alist '(("elixir" . "\\.ex\\'")))
  :config
  (define-hostmode poly-elixir-hostmode :mode 'elixir-mode)
  (define-innermode poly-surface-expr-elixir-innermode
    :mode 'web-mode
    :head-matcher (rx line-start (* space) "~F" (= 3 (char "\"'")) line-end)
    :tail-matcher (rx line-start (* space) (= 3 (char "\"'")) line-end)
    :head-mode 'host
    :tail-mode 'host
    :allow-nested nil
    :keep-in-mode 'host
    :fallback-mode 'host)
  (define-polymode poly-elixir-web-mode
    :hostmode 'poly-elixir-hostmode
    :innermodes '(poly-surface-expr-elixir-innermode)))

(setq web-mode-engines-alist '(("elixir" . "\\.ex\\'")))
```


Hope that helps

**Comment by d3caf** [comment] 2022-01-19 16:07
@anildigital thanks for that! I had forgotten that Doom pins web-mode so I unpinned and updated it. That got rid of the `jit-lock--run-functions` error. However, I'm still seeing the issue where it initially shows highlighting properly and then disappears once I interact with the highlighted section.

**Comment by peterhil** [comment] 2023-01-16 09:44
> I guess you tried it after upgrading both web-mode and polymode.

Thank! Updating web-mode fixed this for me.
