### ISSUE TITLE
many "[yaml]" in A buffer name

### ISSUE THREAD

**Issue by Iorest** [polymode/polymode#194] opened 2018-11-21 06:35 UTC
Sorry for such lame question, but it confuses me that there are too many suffixes，just like ".md[yaml][yaml][yaml]..."，when I exit emacs without kill the buffer, the length will increase when iI reopen emacsn next time.And there will be two or more buffers like "XXX.md[yaml]" and "XXX.md[yaml]".

So how can I fix the problem?

**Comment by vspinu** [comment] 2018-11-21 08:49
That's definitely not right. File example? Versions?

**Comment by Iorest** [comment] 2018-11-21 09:02
![ss](https://user-images.githubusercontent.com/16451699/48830273-2758f080-edaf-11e8-945b-915e2b0e728d.png)


there is an example, I think it will appear when i switch to the buffer with “[yaml]”， I think disable the feature is better.

**Comment by vspinu** [comment] 2018-11-21 09:19
I cannot copy paste that image in my emacs. And again, what are versions of emacs and polymode/poly-R you are using?

**Comment by vspinu** [comment] 2018-11-21 09:39
> I exit emacs without kill the buffer, the length will increase when iI reopen emacsn next 

What do you use to restore your sessions?

**Comment by Iorest** [comment] 2018-11-21 09:42
I use the build-in desktop.el to restore my sessions.

**Comment by vspinu** [comment] 2018-11-21 09:48
Hmm. I cannot reproduced that with desktop-save, desktop-read. Something else is causing it or interaction thereof. If you disable everything except desktop-save-mode and polymode do you still see it?

**Comment by vspinu** [comment] 2018-11-21 09:49
Nevermind. I see it with emacs26. With emacs 27 it's no longer there which means it was an emacs issue with indirect buffers and it's fixed now.

**Comment by vspinu** [comment] 2018-11-21 09:58
Actually it's on emacs27 as well. desctop save cannot handle indirect buffers. I will have a look.

**Closed** 2018-11-21 11:38 UTC

**Comment by vspinu** [comment] 2018-11-21 11:42
Thanks for reporting this. I have implemented a fix. Would really appreciate if you could confirm that it worked for you.

**Comment by Iorest** [comment] 2018-11-21 11:48
Thx, it fix my problem.
