### ISSUE TITLE
Cursor jumps to start of line

### ISSUE THREAD

**Issue by rishisubramanian** [polymode/polymode#188] opened 2018-10-30 17:43 UTC
I have a custom innermode for recognizing inline Latex in Org files. It recognizes anything between `\(` and `\)` as Latex-mode. It works well, but sometimes when I add a new math expression, the cursor jumps to the beginning of the line. It then does this whenever I try to insert a new character. The only way I've found to fix this is to use `revert-buffer`.

Emacs 26.1
Spacemacs Develop Branch

**Comment by vspinu** [comment] 2018-10-30 18:47
So after revert you don't see this anymore? What actions do lead to such behavior? 

Such point jumping can be due to different point locations in indirect buffers. Polymode syncronizes poitns on every occasion but something manages to unsynchronize it. If you can reproduce it reliably I would like to see your modes and reproduce it myself. It's hard to be more specific in this case.

**Comment by kleinschmidt** [comment] 2019-01-15 20:33
This happens to me in normal poly-markdown mode with `$`.  I've also encountered it inside a code chunk where a different mode is active, and a `$` is erroneously picked up as latex  Then the cursor jumps to the start of the line after every keystroke (sometimes on the next line).

**Comment by rishisubramanian** [comment] 2019-01-15 20:51
My theory is that my laptop is too slow to keep up with the changes, since it went away after I optimized my config. Would you mind sharing your specs?

**Comment by vspinu** [comment] 2019-01-16 12:49
> I've also encountered it inside a code chunk where a different mode is active, and a $ is erroneously picked up as latex

Could you share an example?

Regarding the cursor jumping, I do have a reproducible example with noweb and save-buffer, but haven't had time to debug yet.

**Comment by malcook** [comment] 2019-02-19 20:49
I have been suffering with this for some time as well.  

Thanks @rishisubramanian for the suggestion to work-around with `revert-buffer`. 

It is now occurring for me immediately after using org-insert-structure-template (C-c C-,) to create an R code blocks in ESS mode.

I ONLY happens in R/ESS blocks.

It seems intermittent - like there may be some clock/timing issue involved.

**Comment by rishisubramanian** [comment] 2019-02-20 00:32
I suspect it might be due to some delay in processing. I only
encountered the problem on my really slow laptop, and it went away
once I optimized my Emacs config. Are you using a distribution like
Spacemacs?

**Comment by malcook** [comment] 2019-02-20 02:00
I agree with the delay hypothesis and have just now found the origin of mine, which when resolved, solves this issue for me.  I intend to report this issue under separate issue.

**Comment by vspinu** [comment] 2019-03-11 13:36
I know of one reproducible example involving save-buffer which is now fixed in master. I understand the phenomena pretty well, but unfortunately I don't have a full proof solution ATM. It should be tackled case by case. @malcook, I don't see `org-insert-structure-template` in my distribution. Would really appreciate if you could put together an example. Thanks!

Closing this for now as there is little to work with.

**Closed by vspinu** 2019-03-11 13:36 UTC

**Comment by vspinu** [comment] 2019-03-12 15:59
I have just discovered yet another reason for these jumps related to the font-lock and thus, potentially dependent on the hardware speed.  I am pretty confident this issue should be gone now.
